# Generated by Django 3.2.19 on 2023-06-27 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', help_text='Цвет в формате HEX, который будет относится к данному тегу', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Введите значение в формате HEX', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='цвет в HEX'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Уникальное имя-слаг для данного тега', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Введите уникальный слаг', regex='^[-a-zA-Z0-9_]+$')], verbose_name='уникальный слаг'),
        ),
    ]
