# Generated by Django 3.2.19 on 2023-07-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_favorites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ('id',), 'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
