# Generated by Django 3.2.19 on 2023-07-15 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230714_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.PositiveIntegerField(help_text='Количество указанного ингредиента', validators=[django.core.validators.MinValueValidator(1, message='Введите количество >=1.'), django.core.validators.MaxValueValidator(50000, message='Введите количество <= 50000.')], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Время, необходимое для приготовления блюда в минутах', validators=[django.core.validators.MinValueValidator(1, message='Введите время в минутах >=1.'), django.core.validators.MaxValueValidator(32000, message='Введите время в минутах <=32000.')], verbose_name='время приготовления в минутах'),
        ),
    ]
