# Generated by Django 3.2.19 on 2023-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Электронный адрес, с которым будет связана учетная запись пользователя', max_length=254, unique=True, verbose_name='адрес электронной почты (email)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Имя пользователя', max_length=150, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Фамилия пользователя', max_length=150, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Пароль от учетной записи', max_length=150, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text='Роль зарегистрированного пользователя', max_length=15, null=True, verbose_name='пользовательская роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя пользователя, под которым будут видны рецепты и комментарии', max_length=150, unique=True, verbose_name='имя пользователя (логин)'),
        ),
    ]
