# Generated by Django 3.2.19 on 2023-07-03 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Количество указанного ингредиента', validators=[django.core.validators.MinValueValidator(1, message='Введите количество >=1.')], verbose_name='количество'),
            preserve_default=False,
        ),
    ]
