# Generated by Django 3.2.19 on 2023-07-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
